### PR TITLE
Setting flex-shrink to zero on the last items sometimes was still shrinking it with 1 pixel

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Review by hshristov — APPROVED** [review]

**Comment by vchimev** [comment]
uitests

**Comment by vchimev** [comment]
uitests

**Comment by vchimev** [comment]
widgets-uitests-android

**Comment by vchimev** [comment]
widgets-uitests-ios

**Comment by vchimev** [comment]
widgets-uitests-ios

**Comment by vchimev** [comment]
widgets-uitests-android

**Review by vchimev — APPROVED** [review]

**Pull request merged**
