### PR TITLE
fix(Android): better Async error handling

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] You have signed the [CLA](http://www.nativescript.org/cla). 
- [x] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?

Android can become unstable due to improper error handling around async requests.

## What is the new behavior?

Better error condition handling which allow core modules to handle more appropriately.

### CODE REVIEW

**Comment by NathanWalker** [comment]
The `Async` class also is the only one to make exclusive calls to `e.printStackTrace` however I would argue that should not be used and instead a standard log as described here:
https://stackoverflow.com/questions/3855187/is-it-a-bad-idea-to-use-printstacktrace-in-android-exceptions

I can modify to use Log per core team suggestion so leaving commented in these changes for now.

**Comment by vchimev** [comment]
Hey @NathanWalker,

Could you please replace `e.pinrtStackTrace()` with `Log` and clean up the comments and formatting in order to proceed with merging?

Thank you!

**Comment by vchimev** [comment]
test

**Comment by NathanWalker** [comment]
@vchimev I have updated to use `Log` now and formatted - not sure why it shows entire file formatted though. Looks like all other files are formatted using 4 spaces which this one is now as well. Was it not properly formatted on master originally using Tabs? Lemme know if something else I need to do with formatting on this `Async.java` file but other than that should be good?

**Comment by vchimev** [comment]
Thank you, @NathanWalker!

I just replaced `Log.v()` with `Log.e()` and also checked out the formatting.

On its way to `master`.

**Comment by vchimev** [comment]
test

**Comment by NathanWalker** [comment]
Hooray @vchimev thanks!

**Pull request merged**
